module.exports = {
  User: {
    account: '0x55c2d4e04b12081c05481ffeffe47b6e4b9d8fcd',
  },
  RPC: {
    local: 'http://localhost:8545',
    azure: env.AZURE_RPC,
  },
  UserContract: {
    ABI: [{ constant: true, inputs: [], name: 'getUsers', outputs: [{ name: '', type: 'bytes32[]' }, { name: '', type: 'bytes32[]' }, { name: '', type: 'bytes32[]' }, { name: '', type: 'uint256[]' }, { name: '', type: 'uint256[]' }], payable: false, type: 'function' }, { constant: true, inputs: [{ name: '', type: 'uint256' }], name: 'peopleList', outputs: [{ name: '', type: 'bytes32' }], payable: false, type: 'function' }, { constant: true, inputs: [{ name: '_email', type: 'bytes32' }, { name: '_password', type: 'bytes32' }], name: 'authenticateUser', outputs: [{ name: 'success', type: 'bool' }], payable: false, type: 'function' }, { constant: false, inputs: [{ name: '_email', type: 'bytes32' }, { name: '_amount', type: 'uint256' }], name: 'setFundraiserAmount', outputs: [{ name: 'success', type: 'bool' }], payable: false, type: 'function' }, { constant: false, inputs: [{ name: '_email', type: 'bytes32' }, { name: '_filehash', type: 'bytes32' }], name: 'setFilehash2', outputs: [{ name: 'success', type: 'bool' }], payable: false, type: 'function' }, { constant: false, inputs: [{ name: '_email', type: 'bytes32' }, { name: '_filehash', type: 'bytes32' }], name: 'setFilehash1', outputs: [{ name: 'success', type: 'bool' }], payable: false, type: 'function' }, { constant: false, inputs: [{ name: '_email', type: 'bytes32' }, { name: '_status', type: 'uint256' }], name: 'setStatus', outputs: [{ name: 'success', type: 'bool' }], payable: false, type: 'function' }, { constant: true, inputs: [], name: 'getPeopleCount', outputs: [{ name: 'count', type: 'uint256' }], payable: false, type: 'function' }, { constant: true, inputs: [{ name: '_email', type: 'bytes32' }], name: 'getUserDetails', outputs: [{ name: '', type: 'bytes32' }, { name: '', type: 'bytes32' }, { name: '', type: 'bytes32' }, { name: '', type: 'bytes32' }, { name: '', type: 'uint256' }, { name: '', type: 'uint256' }], payable: false, type: 'function' }, { constant: true, inputs: [{ name: '', type: 'bytes32' }], name: 'people', outputs: [{ name: 'email', type: 'bytes32' }, { name: 'password', type: 'bytes32' }, { name: 'filehash1', type: 'bytes32' }, { name: 'filehash2', type: 'bytes32' }, { name: 'status', type: 'uint256' }, { name: 'fundraiser_amount', type: 'uint256' }], payable: false, type: 'function' }, { constant: false, inputs: [{ name: '_email', type: 'bytes32' }, { name: '_password', type: 'bytes32' }], name: 'addUser', outputs: [{ name: 'success', type: 'bool' }], payable: false, type: 'function' }],
    Address: '0x3e8a005e5276bb9fed846878d523f8742b01eff7',
  },
  BankContract: {
    ABI: [{ constant: true, inputs: [], name: 'getCoins', outputs: [{ name: '', type: 'bytes32[]' }, { name: '', type: 'bytes32[]' }, { name: '', type: 'uint256[]' }, { name: '', type: 'bytes32[]' }, { name: '', type: 'uint256[]' }, { name: '', type: 'uint256[]' }], payable: false, type: 'function' }, { constant: false, inputs: [{ name: '_coin', type: 'bytes32' }], name: 'setOwnerAmount', outputs: [{ name: 'success', type: 'bool' }], payable: false, type: 'function' }, { constant: false, inputs: [{ name: '_coin', type: 'bytes32' }, { name: '_to', type: 'address' }, { name: '_amount', type: 'uint256' }], name: 'transfer', outputs: [{ name: 'success', type: 'bool' }], payable: false, type: 'function' }, { constant: false, inputs: [{ name: '_coin', type: 'bytes32' }, { name: '_rating', type: 'uint256' }], name: 'setRating', outputs: [{ name: 'success', type: 'bool' }], payable: false, type: 'function' }, { constant: true, inputs: [{ name: '_coin', type: 'bytes32' }], name: 'getStatus', outputs: [{ name: '', type: 'uint256' }], payable: false, type: 'function' }, { constant: true, inputs: [{ name: '', type: 'uint256' }], name: 'list', outputs: [{ name: '', type: 'bytes32' }], payable: false, type: 'function' }, { constant: true, inputs: [], name: 'owner', outputs: [{ name: '', type: 'address' }], payable: false, type: 'function' }, { constant: false, inputs: [{ name: '_coin', type: 'bytes32' }, { name: '_status', type: 'uint256' }], name: 'setStatus', outputs: [{ name: 'success', type: 'bool' }], payable: false, type: 'function' }, { constant: true, inputs: [{ name: '', type: 'bytes32' }], name: 'ICO', outputs: [{ name: 'name', type: 'bytes32' }, { name: 'symbol', type: 'bytes32' }, { name: 'upperCapAmount', type: 'uint256' }, { name: 'ownerShip', type: 'bytes32' }, { name: 'filehash1', type: 'bytes32' }, { name: 'filehash2', type: 'bytes32' }, { name: 'rating', type: 'uint256' }, { name: 'status', type: 'uint256' }], payable: false, type: 'function' }, { constant: true, inputs: [{ name: '_coin', type: 'bytes32' }, { name: '_owner', type: 'address' }], name: 'balanceOf', outputs: [{ name: 'balance', type: 'uint256' }], payable: false, type: 'function' }, { constant: false, inputs: [{ name: '_name', type: 'bytes32' }, { name: '_symbol', type: 'bytes32' }, { name: '_upperCapAmount', type: 'uint256' }, { name: '_ownerShip', type: 'bytes32' }, { name: '_filehash1', type: 'bytes32' }, { name: '_filehash2', type: 'bytes32' }], name: 'createNewCoin', outputs: [{ name: 'success', type: 'bool' }], payable: false, type: 'function' }],
    Address: '0x97cf15b7cd5d6ca79b4cf654461f565763da7986',
  },
}